### ISSUE TITLE
MSA 환경에서의 서비스 간 통신 URL 설정 수정

### ISSUE THREAD

**Issue by RyuChaeHyun** [Picktartup/Pickstartup-walletservice#35]
## ✨ 기능 설명
기존 워커노드 IP 기반 통신 방식에서 EKS 로 가벼운 로직이 마이그레이션 됨에 따라 도메인 기반 통신으로 전환이 필수적입니다. 

MSA 환경에서 온프레미스와 EKS 간의 서비스 통신을 위한 URL 설정을 개선합니다. 

## ⚠️ 중요도
4 - 서비스 간 통신은 핵심 기능으로 안정적인 운영을 위해 우선적으로 개발이 필요합니다.

## ☑️ 작업 상세 내용
- [ ] application.yml 파일의 서비스 URL 업데이트
 ```yaml
service:
  user:
    url: https://picktartup.com
  startup:
    url: https://picktartup.com
  wallet:
    url: http://192.168.0.142:32450/wallet
```
- [ ] WebClient 설정 개선
- HTTP -> HTTPS 전환
- 리디렉션 처리 추가
- Content-Type 및 Accept 헤더 설정
- 타임아웃 설정

## 📎 참고할만한 자료

> **현재 발생하는 에러:**
Copy301 Moved Permanently from GET http://52.79.224.52/api/v1/startups/1
Content type 'text/html' not supported for bodyType=com.picktartup.contractservice.dto.BaseResponse

> **nslookup 결과:**
CopyName: picktartup.com
Address: 43.203.18.0
Name: picktartup.com
Address: 52.79.224.52
